// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
   
    appId: '1:207347177703:web:a7e8646cb8be7df7baea42',
    messagingSenderId: '207347177703',
    projectId: 'medisure-2024',
    authDomain: 'medisure-2024.firebaseapp.com',
    storageBucket: 'medisure-2024.firebasestorage.app',
    measurementId: 'G-4HGXSBQR2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC4NiZ_Nukaaf-LyRwseYd7RC--r4V5Gg',
    appId: '1:207347177703:android:8b1b06b67c357f65baea42',
    messagingSenderId: '207347177703',
    projectId: 'medisure-2024',
    storageBucket: 'medisure-2024.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpR9o55WOXZkbwDuQF2Jb4purnN18L89I',
    appId: '1:207347177703:web:3a31f723f1c6aee6baea42',
    messagingSenderId: '207347177703',
    projectId: 'medisure-2024',
    authDomain: 'medisure-2024.firebaseapp.com',
    storageBucket: 'medisure-2024.firebasestorage.app',
    measurementId: 'G-53TR8SVNDR',
  );

}
